/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Academic Atelier tokens (from ui-design Stitch HTML)
        'tertiary-container': '#007e37',
        'surface-bright': '#f7f9fb',
        'on-tertiary-fixed': '#002109',
        'on-primary-fixed': '#00174b',
        'on-tertiary-container': '#c1ffc5',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#3f465c',
        'surface-dim': '#d8dadc',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed-variant': '#005321',
        'outline-variant': '#c3c6d7',
        'on-surface': '#191c1e',
        outline: '#737686',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        primary: '#004ac6',
        'error-container': '#ffdad6',
        'primary-container': '#2563eb',
        'on-secondary-container': '#5c647a',
        'on-error-container': '#93000a',
        surface: '#f7f9fb',
        'on-primary-container': '#eeefff',
        secondary: '#565e74',
        'surface-container-highest': '#e0e3e5',
        'on-surface-variant': '#434655',
        'tertiary-fixed-dim': '#4ae176',
        'surface-container': '#eceef0',
        'on-error': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'secondary-container': '#dae2fd',
        'inverse-primary': '#b4c5ff',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed': '#131b2e',
        'secondary-fixed': '#dae2fd',
        'surface-tint': '#0053db',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        tertiary: '#006229',
        'on-primary-fixed-variant': '#003ea8',
        'secondary-fixed-dim': '#bec6e0',
        'surface-container-low': '#f2f4f6',
        'primary-fixed-dim': '#b4c5ff',
        'on-background': '#191c1e',
        'primary-fixed': '#dbe1ff',
        background: '#f7f9fb',
        'tertiary-fixed': '#6bff8f',
        'surface-container-high': '#e6e8ea',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        // soft ambient shadows (tinted with on-surface @ 6%)
        float: '0 32px 64px -12px rgba(25, 28, 30, 0.06)',
        lift: '0 8px 32px -4px rgba(25, 28, 30, 0.08)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}

